server:
  port: 9527
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/my_server?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: my_server
    password: my_server
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  tokenHeader: my-token #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer   #JWT负载中拿到开头

swagger:
  enabled: true
  title: 管理系统-API
  version: v-1.0.0
  authorization:
    key-name: my-token
  docket:
    book-api:
      title: 管理系统-API-api
      version: v-1.0.0
      basePackage: com.my.web
